from __future__ import annotations

from pydantic import Field

from app.models.base import BaseData


class Recommendation(BaseData):
    """
    One recommendation generated by an agent.
    """

    title: str

    description: str

    priority: str

    confidence: float = 0.0

    evidence: list[str] = Field(
        default_factory=list
    )


class AgentReport(BaseData):
    """
    Standard output from every specialist agent.
    """

    agent: str

    score: int

    summary: str

    strengths: list[str] = Field(
        default_factory=list
    )

    weaknesses: list[str] = Field(
        default_factory=list
    )

    recommendations: list[
        Recommendation
    ] = Field(
        default_factory=list
    )